apiVersion: v2
name: pn-backstage
description: Backstage Developer Portal for PN Infrastructure
type: application
version: 0.1.0
appVersion: "1.32.1"

dependencies:
- name: backstage
  version: 1.10.0
  repository: https://backstage.github.io/charts
