---
# System settings role handlers
- name: reload systemd
  systemd:
      daemon_reload: true
  listen: reload systemd

- name: restart systemd-modules-load
  systemd:
      name: systemd-modules-load
      state: restarted
  listen: reload kernel modules

- name: apply sysctl settings
  command: sysctl --system
  listen: apply sysctl

- name: reload sysctl
  systemd:
      name: systemd-sysctl
      state: restarted
  listen: reload sysctl
