apiVersion: v2
name: pn-ingress-nginx
description: NGINX Ingress Controller with custom security and performance configuration
type: application
version: 0.1.0
appVersion: "v1.14.0"

keywords:
  - ingress
  - nginx
  - loadbalancer
  - http

maintainers:
  - name: Platform Team
    email: snoorullah@proficientnowtech.com

dependencies:
  - name: ingress-nginx
    version: 4.14.0
    repository: https://kubernetes.github.io/ingress-nginx
