cert:
  enabled: true

gardenercert:
  enabled: false

deployment:
  version: 1.5.0
  tls:
    name: kubevirt-manager-server-tls
  ingress:
    host: kubevirt.pnats.cloud
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      external-dns.alpha.kubernetes.io/ttl: "60"
  service:
    name: kubevirt-manager
    port: 8080
