apiVersion: v2
name: pn-keycloak
description: Keycloak Identity Provider for PN Infrastructure
type: application
version: 0.1.0
appVersion: "25.2.0"

dependencies:
- name: keycloak
  version: 25.2.0
  repository: https://charts.bitnami.com/bitnami
