apiVersion: v2
name: pn-tempo
description: Tempo distributed tracing for PN Infrastructure  
type: application
version: 0.1.0
appVersion: "2.0.0"

dependencies:
  - name: tempo
    version: 1.24.0
    repository: https://grafana.github.io/helm-charts
