apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redis.redis.redis.opstreelabs.in
  annotations:
    cert-manager.io/inject-ca-from: "redis-operator/webhook-server-cert"
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisclusters.redis.redis.opstreelabs.in
  annotations:
    cert-manager.io/inject-ca-from: "redis-operator/webhook-server-cert"
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisreplications.redis.redis.opstreelabs.in
  annotations:
    cert-manager.io/inject-ca-from: "redis-operator/webhook-server-cert"
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redissentinels.redis.redis.opstreelabs.in
  annotations:
    cert-manager.io/inject-ca-from: "redis-operator/webhook-server-cert"
