apiVersion: v2
name: infisical
description: "Infisical - open-source secret management platform"
type: application
version: 0.1.0
appVersion: "1.17.0"

keywords:
- secrets
- security
- management
- credentials
- kubernetes

annotations:
  category: Security
  platform.pn-infra.io/component: infisical
  platform.pn-infra.io/sync-wave: "300"
