---
apiVersion: v1
kind: Service
metadata:
  name: temporal-frontend-external
  namespace: temporal
  annotations:
    external-dns.alpha.kubernetes.io/hostname: temporal.pnats.cloud
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  type: LoadBalancer
  ports:
  - name: grpc
    port: 7233
    targetPort: 7233
    protocol: TCP
  selector:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: frontend
