apiVersion: v2
name: temporal
description: Highly Available Temporal deployment with PostgreSQL backend
type: application
version: 0.1.0
appVersion: "1.24.2"
dependencies:
- name: temporal
  version: "0.41.0"
  repository: https://go.temporal.io/helm-charts
