apiVersion: v2
name: temporal
description: Highly Available Temporal deployment with PostgreSQL backend
type: application
version: 0.1.0
appVersion: "1.29.1"
dependencies:
  - name: temporal
    version: "0.50.6"
    repository: https://go.temporal.io/helm-charts
