---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kargo-admin-secret
  namespace: kargo
spec:
  encryptedData:
    ADMIN_ACCOUNT_PASSWORD_HASH: AgAzMeJFPT2hgFPfJ2aArxctV9NCizLcizfvY/mo+WOrpKqzpWrEkrqZ8amtkTw5cHVizezuNYH2qb4WwjzyvilOFoABrK3uLPPllPgIcqUr3fv6t04OhioaPjs59V0HEkcxuC+NaAstM8WhXUtm+CWbULUUwZLhQLmpIbAcPXKO3aNySuSY6yfd9WEHbr8k8OqNxmA7D3f1Ww2Ffz7TZkzsnzVvpVnyQkLi3ziGNujVnP0crdOO2m0bWYbOTqx/nP5+8NlaqVKkUB2u62D8td62t3slr+oECOCjDPNvzs0aQfXcFI0oBj0LvBdu0wly31HopyGwhaseizvB2N8y9apsugyoOP6gXHC3xHEDtqCJZYrWokzPMcj4XYyiYuh1B+nh17tnxtZ2oaVODsNUxlPIFSlLzOJeWWzMGBzwUNIRbSlNqhgQZoCVdv4EoZaGwfAHMxU6Z3jz+IG2eUP2/h0fRtJ1k6V97JPBRfUwfbpG0UjTYN43ki6tafBmLExzSUDSmBq2IIEod+UimifFuzwx+qnOZEWWj6WyjSSfd2rOIY5h2PBwO+5Y+PJbj7LgVWPbloIvzLLsrU3lfJH2OLvG1EMNaFoZ2TcEaCxr8zORjYMwKbJCQUlKc+5/4y4KTkpZeflbOJU4W7zlDtlrc5LMhgE2uJkMFBEdbuo3LZi341bB7arX5M4zRYOtOEdq3aAFYfDbtHvDx1EQnRvQFfJBad3H1xQiL9cmoB0Bv6ssht1ue/A9T72AzgPwv25LfMX/yCnwTvrURCS5axI=
    ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: AgCav5Ft80v2XIGNnaLY6Hj9O1GEz2EUfVA3zcM7FDtD14l7atrz92fCHMdkHPXW7yZCcQLlf2oevIrvQSmyapA8QbIujLhP/40UIABkm0AOtXG/AbFWNN73BbZ4qPOeqcujhFKxEVtmS4PmMeojvSVWPmUNBIazoEmpg/j/lP86h+bKo2NdHIzq2PoYJhP2O9j9XrCGlu1r3fYzfvSuuyrnc2p3VoyVAk9q3SyoddLLVIqKbIhN0DstgN1DVlbfN3Il1d+QfEdM51SC2DTjvbEyyMbhfYSnJ7+uexhquKfHSJRoQJVySzQ3ZjBpRNc+qUFwqSzRzpOGG29PGpMYKjt9xRj8quKfCEPoDBHGTTo2E4FP2yuMZXp2rtUasaR9CaajpysRwoJEFwBnZuQJMek3oqQsfI8nyeQZahtLjcWRd2oPEndMAmDBNNIpSuHCpJRbSI7+u+33Zel5Ycn+HuYH0QE9b03eax2ACQ1a4MvF0qTOLaQfYlECsC1dCqQmwyg9F0xkFGfayfNCK2kQQ2kn2G4z8nDgNILJDHz1SGM9rakqybgg8OF8vbDguTby+FanzPbI8KLachrf0pAWDMM3GH0n96Zq89NpfwBtEFDO1i1EcV9T+bhJyMHCQ57MGLYsd63/ntAeRJkxdWHPNEipoWXS2/nM4R2ON8Y6t1NIJVWdeWDysxjMRcOHpe4t1nRCk0Ylz7qd20VU+T1M29hLXf421rgdbdAG9Q0fBCVotg==
  template:
    metadata:
      name: kargo-admin-secret
      namespace: kargo
    type: Opaque
