---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  encryptedData:
    github-token: AgCTcybLlyyBHUbx/bHX5y1SEVmm/vQY/VnE7nMPCUCtxF4wXrq88MziLgh/0M4b84pgwgOyBXw/vpnbTXPFPFCaWKHbg1wTOQkM99+NMFOrTMjDXv4va0rgPsly2bSz27voAKF3RJb4pXL1Al9PzX5We6Ws0s7pXqmKh50sUOcdpDxjux8r3YlyErYuIVUEMD87R8yjyWd/CPligl3ODT4qShZyKZvqCzAm1KWcX19dAHxMMXP0s7zNCtrshY2xAoVHBrSgewNv6uxXdEF9zCvv9RmCled3ZammyT+zQIByCjHizAFxPQzeWi8HKj0adgPjdXBrB3fIjr71o1S4IneJ+KzwR7GNYGvtvCUpcOtH1c9cotSPJqKpwxSp0Xj7nN9mc8Al+0Q8I4dJkI3X1GIixkyHf8z+lbsBJWCiSsU4Ama18t78RI1higrfJmOaDh+jkWuHUx4aATKDSKI1PYfaJop1xnFgkzdEyvjrIg+O9EDEdQ4A7Lxve3h0AngO4gTjMk7HP7dmXlOyttscWMfNcpTD/qaVJSiYTONvRcm0d/A/ydgt0xu3MC9BJpz85gYBEUqO6c/kh7Mlmy1ydijvgAoV6Q4VhYI8N+AD7oy9KosSjc+Gs+ReEQw3zp7RtUEYIThcJyllqShOequH/3vye9OrAj8CP59FsTlT+z5NdOASxvIwA/2tq4vdPR0HmuMuMwcUnSH+RQZnOkQPY+7bYBxKNvVGI7RDmRCO8pMNUf3uRFw7SEcMgvC/IKgJPdir3/C+NOldyg==
    keycloak-client-secret: AgAAPTpv0PG8CgtcUhmx11uplF3QfFKgHgOso62Jv4AzWin5nsFyWkLfgdRrRfZled3N4Ri0iHT2NH6cMhcHGMrFCdujH1GAx5GgU9ECLFuBPVgfJP4RVKWARakIqCHE7zw9Nvmww4VqmtpXgb5M8Xp8psdfi/3YzuT40l70W6tGo0dlYFoUJX7qfkxN7uBVR8WwgthbYnoqnamfh3E2uQwMLK5YpGNLJ43lkkR7HbxWedwD5X/0rqHKb0l4NZlWoNaQ/Q2X82XcztO46b9ehI5lk9aTfx2t2PQr+iHz1AFoMXnW5tAvWkZIz0mQOEx/ZBkCo11yVYqmp4yKBCsZmI7xJlIDeDpfDMr6dnkGi15o66rY31ssx0XJm3RePhCWyYTM/7ZkVRcuSGEoeZu0k5OPf2IEYEv4iFg+aziHe0yFEcajxNOdEpnch2Po4sNN8PDM8ndkGiOE2/VBPFA3lwG9O0yRs0g/R+zKXqCjdmfGzczwQXaQ2SfM824+vQYdaiXIwxEMCaEgRSchAqgZ1HtSEYlMFKSM0Hmy2ara2eRKR2e9wln30EswGOTG8aRkHlJOrdWNrJrZk1PScOuzut6lf5Qanku7F5Qa+PQE0OY/PUuhttw4MhmBnX02SPXg5Nb/9vf8/S+z9+MbElF7PyW1SxROCgDciGK88TVR4qDMfzZ2YGis5GAK9Nrc62X9JgnBl/0t7paLMNu0muhdZC++0Y/NX/oWJwJb3smtBvZrlNbOARht/67wj9eJwg==
  template:
    metadata:
      annotations:
        description: Backstage Credentials Secrets
      name: backstage-secrets
      namespace: backstage
    type: Opaque
