apiVersion: v2
name: pn-uptime-kuma
description: Uptime Kuma monitoring for PN Infrastructure
type: application
version: 0.1.0
appVersion: "1.23.16"

dependencies:
  - name: uptime-kuma
    version: 2.22.0
    repository: https://dirsigler.github.io/uptime-kuma-helm
