apiVersion: v2
name: pn-prometheus
description: Prometheus monitoring stack for PN Infrastructure
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: 65.1.1
    repository: https://prometheus-community.github.io/helm-charts
