---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: temporal-postgres-secret
  namespace: temporal
spec:
  encryptedData:
    password: AgA15Ni5HMmpE+bW4P3OXOOGdaMz8MNvfduZQ5vKbfwp9z621fu/HhJhHi14DX3HSEuUe08vtmNF70MQzC+FdSFg0l6w9LhNKmBF/F2FvRwi725zkivkDVgc0cRKbkoSupuCgSszAs7NKgPPnMarI3SKyEBHa7xcsSNPocSzOAp7J8poQgLwY7Ticn+8+Wnr3VFtB+Bzm7xxNPKqE4yx1xjeA0Fr6/VZ13olgqDhRcPmzPL0O2XgI0z+N4S7GDpYSfYvSKHNbHYMnDsxh16k1pegw100jDN0Es011V0SuZL8NOn6mMFl4NEUr87gjB6Hm4ghKAz3y5KZxkl6iwQ9c0OROX8R6HJ5VGTa/xULxQUE1rP9lP1iabzlsjbps0sr4+POM3YxbxBu3/NWfRT1aouVDWHnqOeb+ecgL6qHXU2L6n+p67hTi/+UhwI3Od3MjyHXYgBLqNOLieLglbqJmXtntGSNY6PR2Ew+L5ZD7jI63bK+bqcNTmFNIh0taM7jxibh3hShQrz7qK06QH3y/zj1oGETcuscEIwjNwxo4eA+AL5V7HH81QFRTiGe7RwWkmq/jdNCMS9hJw7oC311zDbqj8RShSOM0zRsOcLF2/5rvca1HQDr4mD6T8nvEMf3+OowcgT3LjztvL/JrlLApiSk+Mz1IajArG5qUWylkQBG9amG3E4Hzo3xiecxSIrrThuGwY+1VbRPJ3JOVUGjSDe1dyyPkarfPjjDG6vNCZ0THqBj5I1pBq6Awgpfyw==
    postgres-password: AgAEbp9L7FaG9ao5jqypvO1+hTofcUlFGrUvOvvkz9RpDEH0jimeOX3KgfZQig16V005F+fvzOjCNXcq9fFEAd1EG488UgLLBx0QQlbiRFL7mHdVwFPzDwgiRCVJViUIsPCc2z2jw74falMR3rIMennmr5V2LuBVPlPhf3hqoN76vveuzcNsEm3KwhGndi8JaoqdVQ1sfBJFltPuKHX18ZIjlCF/WDL2x2Av+dzdkoHHzVmRX6hBUrQISvqlAMOtGHWVFjvkxF3v5AnbKL2399tJwZQZD+GU/MRcw8YlLGqdTCpfBbhlPyBeQS7lwAdfkJrGfXKjHvBhqocaVT3E+2T+h56u1lM3jXS6AFRFVWmxLz0AhmN3qRzSRbZzfjLmJKVuV/5VNlEwnP8BeLkmEUPp1n/p2gkdEafxGq0xaTDFn3NrBuMljNnBVFJD5iAqtvesMPOtJD0N93MtPOG2p8tU84G3EEI95yuUtyDRlCuXplDq6Kp/r3o6plxCo88QzKq4y7HwWej4OljNFZAgbcJKczULhh9OaT9XCK1Pmpmeta7kIyN3JelADOJ5Ln2UeIqupbX8zXm1HHwpWS+S0iH89lNVxyAlsYJeLiSn4Qp5kv17yAVtGcNTw7a2vCyJ4XdqYfPGhUjRNrJlCRMXNp+eK3EZpbcuysQn7w9J0tOZ/n62+61uYdrCOFWsWjUDMpBFp8c5qmPas01w5FJL1eHSVnEmovBOQjPOOc+ra5g6qK0GVJqJ3FaSiM2jmQ==
  template:
    metadata:
      name: temporal-postgres-secret
      namespace: temporal
    type: Opaque
