kubevirt:
  version: v1.5.0
cdi:
  version: v1.62.0
datasources:
  enabled: true
  sources:
  - name: ubuntu-jammy-server
    url: http://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
    storage: 3G
    # description for backstage Software Catalog
    description: ubuntu 22.04 Base Image
