---
# Disk management role handlers
- name: reload systemd
  systemd:
      daemon_reload: true
  listen: reload systemd

- name: remount all filesystems
  command: mount -a
  listen: remount filesystems

- name: update initramfs
  command: update-initramfs -u
  when: ansible_os_family == "Debian"
  listen: update boot

- name: rebuild initramfs (RedHat)
  command: dracut --force
  when: ansible_os_family == "RedHat"
  listen: update boot
