---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-s3-credentials
  namespace: harbor
spec:
  encryptedData:
    accesskey: AgB5mEJQ8316xXmHLDc3D49HSOXlN1QH0goP3W9McNa47fhwvXl/WDwSh5loqn6AQjh9X8TFQqtQaNDhI8Qa4Lj5ql7TSDOHPyPggWNYnwLRJto81IK0v1KiHSL+8aCfkawneJHi+Zk7eGazQW3kwDOHV8QC+6Csj5MFF5wgtRU/gxdgKDH8NVQYoFumgueAVeysAFf3/wTd/00uHkkDr4oZr4SqFIQjh09gmn0HFoIsrWQVNlDQ8OSLRO4AF4y+vnZht0RhS0HP8c7q433TrfCFBNmnLQu4szbMRvgR6ufwB1hszEKnSfojkP67owCK095eA+WNG7oU1XX8PHzkL60nImkSP1NX+0jxupMklUpJ31vvEG/GkuE+qzB4y9JxtPiEeLKdxR8fnhd+FWH6VJZNXiSH0MmEjVkUcrBi2PfG6cU3ArwBLL/LwVIk3KNADXvfLgDssGh47vXB82TD8QKJgB9K1LsvRVpWRBG6kXXSgcewGeIMO+Jn41IaaJlp77p4HH866D8X4EFpBKQPN6nWFUD7t8GJ6fel07kqSoO3HyH21agpvljPSlXfaWUNi45f6M3P5VKWDqUhkn9H/Iom2VSdgRpfW6oFs08JSB4VcZjbhv9qeAGqOb9QY5fbjUK2C3qvoUnp876iftl05eo1Hd66u3O5cmEktcUN7joZ8Ci7BtwgO5DtfXxIVK4pTpbDYy1PlL9OalvuSOfq4sGjTocwTQ==
    secretkey: AgBJgM96y0r/a4xNZdPHXn//hWTFrOaKewUvMGCRcOAeJafPRNxxf7OAJLllQEfu4bpVRHjcVVyVsxGrAJjRekjRB062fdsbthDfFyQkcUx0bpfaUeTMq5CTCaMCx/WkJxhHR+rMqe2DiSYTt467scJj6mepZ7gHty/oejJIT0q8KoVDxAV4MafwoANjSqC5LK2UKFrULtykesWpkSzf4y40aCsgcDO5ze+iQ+vNDN4Uwsp9QJYWYwVzo+iHhKVAYBibeDBzGynbpIrXKpoSr2WIDCoWSl7vY2XT3QBuHN+fRo8FV5UNUE7QqW3OP8hP99z7JBjWC0pS5ltRDWfvBxoM+kDqRwzN3Qj5rUekICGkaQ9Iu83BX6wnKlG122iZMFl+lebRerGw5n31F0lO/lQqbTTufgPg0kbWwcllmPqzVeLKjPpZVO6u+PU12HaDI3CXJvi5pE6KvHlnySiiYxmaNFTDcMlMq/Cm6huTQgzp7ZfEJ+WcyXObo02dgxHLkoiD4iNlaFMnAoNP24jGH2blUXysugmgR5VwgYj+pm/HOORygj98Rpwq2Hkq4UvCGId4tvGBvv29lpPDBbJjLTg5baBhiki0SE+7tK0EGn0BktksUE5UB3ILw+tIhCr6RGhWS+CA0KcGUZ+EN1mHuN9HXU9Q08zKuYebWrXfYGORucBrViQeAhb+zj02ww0SEmKljFRCYoTBSoFC8TFGEEnyDLJNx38b0vLtZijMso1ZmLNtrzb5PSNo
  template:
    metadata:
      name: harbor-s3-credentials
      namespace: harbor
