apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert
  namespace: harbor
spec:
  dnsNames:
  - harbor.pnats.cloud
  - registry.pnats.cloud
  secretName: harbor-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
