apiVersion: v2
name: pn-backstage
description: Backstage Developer Portal for PN Infrastructure
type: application
version: 0.1.0
appVersion: "1.44.2"

dependencies:
- name: backstage
  version: "2.6.2"
  repository: https://backstage.github.io/charts
