apiVersion: v2
name: pn-clusterapi
description: Cluster API with KubeVirt provider for PN Infrastructure
type: application
version: 0.1.0
appVersion: "1.8.7"

dependencies:
- name: cluster-api-operator
  version: 0.14.0
  repository: https://kubernetes-sigs.github.io/cluster-api-operator
